### ISSUE TITLE
panic: package golang.org/x/tools/cmd/fiximports/testdata/src/new.com/one: code in directory /builddir/build/BUILD/tools-77106db15f689a60e7d4e085d967ac557b918fb2/_build/src/golang.org/x/tools/cmd/fiximports/testdata/src/new.com/one expects import "new.com/one" [recovered]

### ISSUE THREAD

**Issue by nim-nim** [gofed/symbols-extractor#148]
golist aecba475bf76f5269c11367da0a190419cd9a133 panics while scanning golang-x-tools 77106db15f689a60e7d4e085d967ac557b918fb2
(what the hell is it doing poking in testdata anyway)

As a result, the produced -devel package is empty

```
+ mkdir /builddir/build/BUILDROOT/golang-x-tools-0-0.38.0.20180325git77106db.fc29.llt.x86_64
+ cd tools-77106db15f689a60e7d4e085d967ac557b918fb2
+ go-rpm-integration install -i golang.org/x/tools -e js -e yaml -e ts cmd/present/static/article.css cmd/present/static/dir.css cmd/present/static/dir.js cmd/present/static/favicon.ico cmd/present/static/jquery-ui.js cmd/present/static/notes.css cmd/present/static/notes.js cmd/present/static/slides.js cmd/present/static/styles.css -s /builddir/build/BUILD/tools-77106db15f689a60e7d4e085d967ac557b918fb2 -b /builddir/build/BUILD/tools-77106db15f689a60e7d4e085d967ac557b918fb2/_build -o devel.file-list -p /builddir/build/BUILDROOT/golang-x-tools-0-0.38.0.20180325git77106db.fc29.llt.x86_64 -g /usr/share/gocode -r '.*example.*'
install: creating directory '/builddir/build/BUILDROOT/golang-x-tools-0-0.38.0.20180325git77106db.fc29.llt.x86_64/usr'
install: creating directory '/builddir/build/BUILDROOT/golang-x-tools-0-0.38.0.20180325git77106db.fc29.llt.x86_64/usr/share'
install: creating directory '/builddir/build/BUILDROOT/golang-x-tools-0-0.38.0.20180325git77106db.fc29.llt.x86_64/usr/share/gocode'
install: creating directory '/builddir/build/BUILDROOT/golang-x-tools-0-0.38.0.20180325git77106db.fc29.llt.x86_64/usr/share/gocode/src'
Installing: golang.org/x/tools
panic: package golang.org/x/tools/cmd/fiximports/testdata/src/new.com/one: code in directory /builddir/build/BUILD/tools-77106db15f689a60e7d4e085d967ac557b918fb2/_build/src/golang.org/x/tools/cmd/fiximports/testdata/src/new.com/one expects import "new.com/one" [recovered]
        panic: package golang.org/x/tools/cmd/fiximports/testdata/src/new.com/one: code in directory /builddir/build/BUILD/tools-77106db15f689a60e7d4e085d967ac557b918fb2/_build/src/golang.org/x/tools/cmd/fiximports/testdata/src/new.com/one expects import "new.com/one"

goroutine 1 [running]:
github.com/gofed/symbols-extractor/vendor/github.com/urfave/cli.HandleAction.func1(0xc420127a10)
        /home/jchaloup/Projects/gofed/symbols-extractor/src/github.com/gofed/symbols-extractor/vendor/github.com/urfave/cli/app.go:472 +0x2c8
panic(0x66f780, 0xc420414f80)
        /usr/lib/golang/src/runtime/panic.go:491 +0x283
github.com/gofed/symbols-extractor/pkg/util.(*PackageInfoCollector).CollectPackageInfos.func1(0xc42021b7a0, 0x8a, 0x7feb60, 0xc42020cc30, 0x7fac20, 0xc420414f80, 0x0, 0x0)
        /home/jchaloup/Projects/gofed/symbols-extractor/src/github.com/gofed/symbols-extractor/pkg/util/util.go:177 +0xa75
path/filepath.walk(0xc42021b7a0, 0x8a, 0x7feb60, 0xc42020cc30, 0xc42000cd20, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:356 +0x81
path/filepath.walk(0xc42021b170, 0x86, 0x7feb60, 0xc42020c8f0, 0xc42000cd20, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:381 +0x3a0
path/filepath.walk(0xc42011cf80, 0x7e, 0x7feb60, 0xc4200708f0, 0xc42000cd20, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:381 +0x3a0
path/filepath.walk(0xc42011ca00, 0x7a, 0x7feb60, 0xc4200705b0, 0xc42000cd20, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:381 +0x3a0
path/filepath.walk(0xc4201b5300, 0x71, 0x7feb60, 0xc4203af860, 0xc42000cd20, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:381 +0x3a0
path/filepath.walk(0xc4200fd1f0, 0x66, 0x7feb60, 0xc42026c1a0, 0xc42000cd20, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:381 +0x3a0
path/filepath.walk(0xc4200202a0, 0x63, 0x7feb60, 0xc420071860, 0xc42000cd20, 0x0, 0x2)
        /usr/lib/golang/src/path/filepath/path.go:381 +0x3a0
path/filepath.Walk(0xc4200202a0, 0x63, 0xc42000cd20, 0x6bba65, 0x1)
        /usr/lib/golang/src/path/filepath/path.go:403 +0x11d
github.com/gofed/symbols-extractor/pkg/util.(*PackageInfoCollector).CollectPackageInfos(0xc42007a640, 0x7ffe568a7953, 0x12, 0x7ffe568a7953, 0x12)
        /home/jchaloup/Projects/gofed/symbols-extractor/src/github.com/gofed/symbols-extractor/pkg/util/util.go:133 +0x169
main.main.func1(0xc42009cb40, 0x0, 0x0)
        /home/jchaloup/Projects/gofed/symbols-extractor/src/github.com/gofed/symbols-extractor/cmd/golist/golist.go:73 +0x9db
reflect.Value.call(0x667860, 0x6cc720, 0x13, 0x6bbe20, 0x4, 0xc4200539b0, 0x1, 0x1, 0xc420053930, 0x6b2680, ...)
        /usr/lib/golang/src/reflect/value.go:434 +0x905
reflect.Value.Call(0x667860, 0x6cc720, 0x13, 0xc4200539b0, 0x1, 0x1, 0x6bba58, 0x1, 0x6bdf54)
        /usr/lib/golang/src/reflect/value.go:302 +0xa4
github.com/gofed/symbols-extractor/vendor/github.com/urfave/cli.HandleAction(0x667860, 0x6cc720, 0xc42009cb40, 0x0, 0x0)
        /home/jchaloup/Projects/gofed/symbols-extractor/src/github.com/gofed/symbols-extractor/vendor/github.com/urfave/cli/app.go:481 +0x180
github.com/gofed/symbols-extractor/vendor/github.com/urfave/cli.(*App).Run(0xc420001800, 0xc4200100c0, 0xc, 0xc, 0x0, 0x0)
        /home/jchaloup/Projects/gofed/symbols-extractor/src/github.com/gofed/symbols-extractor/vendor/github.com/urfave/cli/app.go:240 +0x507
main.main()
        /home/jchaloup/Projects/gofed/symbols-extractor/src/github.com/gofed/symbols-extractor/cmd/golist/golist.go:129 +0x75d

```

**Comment by nim-nim** [comment]
golist now ignores testdata as it should
